name: Nightly Cron

on:
  schedule:
    # 2:30 PST
    - cron:  '30 10 * * *'
  workflow_dispatch:


jobs:

  tests-and-coverage-nightly:
    name: Tests and coverage (pip, Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install .[test]
    - name: Unit tests and coverage
      run: |
        pytest -ra --cov=. --cov-report term-missing
    - name: Upload coverage
      if: ${{ runner.os == 'Linux' && matrix.python-version == 3.7 }}
      run: |
        bash <(curl -s https://codecov.io/bash)

  package-test-deploy-pypi:
    name: Package and test deployment to test.pypi.org
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install .[test]
        pip install --upgrade setuptools wheel
    - name: Build packages (wheel and source distribution)
      env:
        SCM_NO_LOCAL_VERSION: true
      run: |
        python setup.py sdist bdist_wheel
    - name: Verify packages
      env:
        SCM_NO_LOCAL_VERSION: true
      run: |
        ./scripts/build_and_verify_py_packages.sh
    - name: Deploy to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
        verbose: true

  package-conda:
    name: Test conda build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: test
        python-version: "3.7"
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install dependencies
      shell: bash -l {0}
      # Don't need deps for conda build, but need them for testing
      run: |
        conda install -y conda-build
        conda config --set anaconda_upload no
        conda install -y -c pytorch-nightly pytorch cpuonly
        conda install -y scipy
        conda install -y -c conda-forge pyro-ppl==1.8.0
        pip install git+https://github.com/cornellius-gp/gpytorch.git
    - name: Build and verify conda package
      shell: bash -l {0}
      run: |
        ./scripts/build_and_verify_conda_package.sh

  publish-latest-website:
    name: Publish latest website
    runs-on: ubuntu-latest
    needs: [tests-and-coverage-nightly, package-test-deploy-pypi, package-conda]
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install dependencies
      run: |
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install .[dev]
        pip install git+https://github.com/facebook/Ax.git
        # NOTE: nbconvert 6.4.4 is incompatible with jinja2 3.1.0.
        # We can unpin this with a future release of nbconvert.
        pip install beautifulsoup4 ipython nbconvert "jinja2==3.0.3"
    - name: Unit tests
      run: |
        pytest -ra
    - name: Publish latest website
      env:
        DOCUSAURUS_PUBLISH_TOKEN: ${{ secrets.DOCUSAURUS_PUBLISH_TOKEN }}
      run: |
        ./scripts/publish_site.sh -d

  run_tutorials:
    name: Run tutorials without smoke test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Fetch all history for all tags and branches
      # we need to do this so setuptools_scm knows how to set the botorch version
      run: git fetch --prune --unshallow
    - name: Install dependencies
      env:
        # this is so Ax's setup doesn't install a pinned BoTorch version
        ALLOW_BOTORCH_LATEST: true
      run: |
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install git+https://github.com/facebook/Ax.git
        pip install .[tutorials]
    - name: Run tutorials
      run: |
        python scripts/run_tutorials.py -p "$(pwd)"
